
import React, { useState } from 'react';
import { Artifact } from '../types';
import { Button } from './Button';

interface ArtifactCardProps {
  artifact: Artifact;
  onDownload: (artifact: Artifact) => void;
}

// Global declaration for html2pdf
declare var html2pdf: any;

export const ArtifactCard: React.FC<ArtifactCardProps> = ({ artifact, onDownload }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const formatMarkdownForHtml = (content: string) => {
    return content
      .replace(/^# (.*$)/gm, '<h1 style="font-size: 24pt; font-weight: 800; color: #0f172a; margin-bottom: 20px; border-bottom: 3px solid #2563eb; padding-bottom: 10px; letter-spacing: -0.02em;">$1</h1>')
      .replace(/^## (.*$)/gm, '<h2 style="font-size: 18pt; font-weight: 700; color: #1e293b; margin-top: 30px; margin-bottom: 12px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px;">$1</h2>')
      .replace(/^### (.*$)/gm, '<h3 style="font-size: 14pt; font-weight: 600; color: #2563eb; margin-top: 20px; margin-bottom: 8px;">$1</h3>')
      .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #0f172a;">$1</strong>')
      .replace(/^\- (.*$)/gm, '<li style="margin-bottom: 6px; color: #334155;">$1</li>')
      .split('\n\n').map(p => {
        if (p.startsWith('<h') || p.startsWith('<li')) return p;
        return `<p style="margin-bottom: 14px; font-size: 11pt; color: #334155; line-height: 1.6;">${p.replace(/\n/g, '<br>')}</p>`;
      }).join('\n');
  };

  const getInstitutionalTemplate = (companyName: string, dateStr: string) => `
    <div style="padding: 40px; font-family: 'Inter', sans-serif; background: white; color: #1e293b; max-width: 800px; margin: 0 auto;">
      <div style="display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #0f172a; padding-bottom: 15px; margin-bottom: 30px;">
        <div>
          <div style="font-weight: 800; font-size: 16pt; color: #2563eb; text-transform: uppercase; letter-spacing: 0.1em;">EquityResearchPro</div>
          <div style="font-size: 8pt; font-weight: 600; color: #94a3b8; margin-top: 2px;">INSTITUTIONAL GRADE ANALYSIS</div>
        </div>
        <div style="text-align: right; font-size: 9pt; color: #64748b;">
          <div>ENTITY: <strong style="color: #0f172a;">${companyName.toUpperCase()}</strong></div>
          <div>DATE: ${dateStr}</div>
        </div>
      </div>
      
      <div style="margin-bottom: 40px;">
        ${formatMarkdownForHtml(artifact.content)}
      </div>

      <div style="margin-top: 50px; border-top: 1px solid #f1f5f9; padding-top: 15px; text-align: center; font-size: 8pt; color: #94a3b8; font-style: italic;">
        This report is generated by EquityResearchPro AI. Proprietary & Confidential. 
        Information provided is based on point-in-time regulatory filings and is for institutional educational use only.
      </div>
    </div>
  `;

  const downloadAsPdf = async () => {
    setIsGenerating(true);
    const companyName = artifact.filename.split('_')[0] || 'Company';
    const dateStr = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    const element = document.createElement('div');
    element.innerHTML = getInstitutionalTemplate(companyName, dateStr);

    const opt = {
      margin: [10, 10, 10, 10],
      filename: artifact.filename.replace('.md', '.pdf'),
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, letterRendering: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    try {
      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error("PDF generation failed", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const exportToPdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const companyName = artifact.filename.split('_')[0] || 'Institutional';
    const dateStr = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    printWindow.document.write(`
      <html>
        <head>
          <title>${artifact.title} | EquityResearchPro</title>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
          <style>
            body { margin: 0; padding: 0; background: #f1f5f9; }
            @media print {
              body { background: white; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          ${getInstitutionalTemplate(companyName, dateStr)}
          <script>
            window.onload = () => {
              setTimeout(() => {
                window.print();
              }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 flex flex-col hover:shadow-md transition-all h-full group">
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-blue-600/5 rounded-2xl text-blue-600 ring-1 ring-blue-600/10 group-hover:bg-blue-600 group-hover:text-white transition-colors">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <div>
            <h3 className="font-bold text-slate-900 leading-tight tracking-tight">{artifact.title}</h3>
            <p className="text-[10px] font-mono text-slate-400 mt-1 uppercase tracking-widest">{artifact.filename}</p>
          </div>
        </div>
      </div>
      
      <div className="mt-4 flex-1 prose prose-sm max-h-40 overflow-y-auto text-slate-600 border-t border-slate-50 pt-4 scrollbar-thin scrollbar-thumb-slate-200">
        <div className="whitespace-pre-wrap font-mono text-[10px] leading-relaxed opacity-60">
          {artifact.content.slice(0, 400)}...
        </div>
      </div>

      <div className="mt-6 space-y-2">
        <Button 
          variant="primary" 
          className="w-full text-xs py-3.5 font-bold uppercase tracking-widest shadow-lg shadow-blue-500/20"
          onClick={downloadAsPdf}
          isLoading={isGenerating}
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          {isGenerating ? 'Generating...' : 'Download Direct PDF'}
        </Button>
        
        <div className="grid grid-cols-3 gap-2">
          <Button 
            variant="outline" 
            className="text-[10px] py-2 px-1 text-slate-500 uppercase font-bold tracking-tighter"
            onClick={exportToPdf}
            title="Export to Print Dialog"
          >
            Export
          </Button>
          <Button 
            variant="outline" 
            className="text-[10px] py-2 px-1 text-slate-500 uppercase font-bold tracking-tighter"
            onClick={() => onDownload(artifact)}
            title="Download Markdown"
          >
            MD
          </Button>
          <Button 
            variant="ghost" 
            className="text-[10px] py-2 px-1 text-slate-400 hover:text-blue-600 uppercase font-bold tracking-tighter"
            onClick={() => {
              const viewWindow = window.open('', '_blank');
              viewWindow?.document.write(`<pre style="font-family: monospace; white-space: pre-wrap; padding: 40px; background: #f8fafc; color: #334155; line-height: 1.5;">${artifact.content}</pre>`);
              viewWindow?.document.close();
            }}
            title="View Raw Text"
          >
            Raw
          </Button>
        </div>
      </div>
    </div>
  );
};
